christophersompa/phone-case

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsCustomer.cs
Testing1/TestingCustomer.csproj
Testing1/tstCustomer.cs

Adding testing and class for Customer Management

---

ClassLibrary/clsCustomer.cs
Testing1/tstCustomer.cs

creating the properties for customer table

---

ClassLibrary/clsCustomer.cs
Testing1/tstCustomer.cs

changes to the properties for customer table

---

AdminSystem/CustomerDataEntry.aspx
AdminSystem/CustomerDataEntry.aspx.cs
AdminSystem/CustomerViewer.aspx.cs
Skeleton.sln

adding the customer presentation layer

---

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsOrder.cs
Testing4/TestingOrder.csproj
Testing4/tstOrder.cs

Added testing and class for order processing

---

AdminSystem/Web.config
AdminSystem/packages.config
ClassLibrary/clsOrder.cs
Testing1/TestingCustomer.csproj
Testing1/packages.config
Testing2/TestingProduct.csproj
Testing2/packages.config
Testing3/TestingStaff.csproj
Testing3/packages.config
Testing4/TestingOrder.csproj
Testing4/packages.config
Testing4/tstOrder.cs
Testing5/TestingSupply.csproj
Testing5/packages.config
Testing6/Testing6.csproj
Testing6/packages.config

Created propeties for order processing table design

---

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsStaff.cs
Testing3/TestingStaff.csproj
Testing3/tstStaff.cs

Added testing and class for Staff Management

---

AdminSystem/CustomerDataEntry.aspx
AdminSystem/CustomerDataEntry.aspx.cs
ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsCustomer.cs
ClassLibrary/packages.config
Testing1/TestingCustomer.csproj
Testing1/tstCustomer.cs
Testing2/TestingProduct.csproj
Testing2/packages.config
Testing3/TestingStaff.csproj
Testing3/packages.config
Testing4/TestingOrder.csproj
Testing4/packages.config
Testing5/TestingSupply.csproj
Testing5/packages.config
Testing6/Testing6.csproj
Testing6/packages.config

creating the find method (middle layer)

---

ClassLibrary/clsOrder.cs
Testing4/tstOrder.cs

Created the find method and developed the middle layer

---

AdminSystem/packages.config
ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsCustomer.cs
ClassLibrary/packages.config
Skeleton.sln
Testing1/TestingCustomer.csproj
Testing1/packages.config
Testing2/TestingProduct.csproj
Testing2/packages.config
Testing3/TestingStaff.csproj
Testing3/packages.config
Testing4/TestingOrder.csproj
Testing4/packages.config
Testing5/TestingSupply.csproj
Testing5/packages.config
Testing6/Testing6.csproj
Testing6/packages.config

incomplete; needs to connect to sql and test tstcustomer

creating the find method (data layer) incomplete

---

ClassLibrary/clsStaff.cs
Testing3/tstStaff.cs

All checked and is working fine

Added properties to tstStaff in accordance to my table schema

---

AdminSystem/CustomerDataEntry.aspx
AdminSystem/CustomerDataEntry.aspx.cs

minor changes to customer data entry

---

AdminSystem/StaffDataEntry.aspx
AdminSystem/StaffDataEntry.aspx.cs
AdminSystem/StaffViewer.aspx.cs
ClassLibrary/clsStaff.cs
Testing3/tstStaff.cs

Code is partially finished, but all code entered has been checked and is working fine

Started with the middle layer of the project.

---

AdminSystem/StaffDataEntry.aspx
AdminSystem/StaffDataEntry.aspx.cs
AdminSystem/StaffViewer.aspx.cs

made sure all data can be entered within the presentation layer and that the ok button accepts them. The ok button also displays the data entered on the staff viewer page

Finshed creating the presentaion layer

---

ClassLibrary/clsStaff.cs
Testing3/tstStaff.cs

All checked and is working fine

Creating the Find Method (Middle Layer) completed

---

AdminSystem/CustomerDataEntry.aspx
AdminSystem/CustomerDataEntry.aspx.cs

Creating the find method (the presentation layer)

---

AdminSystem/CustomerDataEntry.aspx.cs
AdminSystem/Web.config
AdminSystem/packages.config
ClassLibrary/ClassLibrary.csproj
ClassLibrary/app.config
ClassLibrary/clsCustomer.cs
ClassLibrary/packages.config
Skeleton.sln
Testing1/TestingCustomer.csproj
Testing1/app.config
Testing1/packages.config
Testing1/tstCustomer.cs
Testing2/TestingProduct.csproj
Testing2/app.config
Testing2/packages.config
Testing3/TestingStaff.csproj
Testing3/app.config
Testing3/packages.config
Testing4/TestingOrder.csproj
Testing4/app.config
Testing4/packages.config
Testing5/TestingSupply.csproj
Testing5/app.config
Testing5/packages.config
Testing6/Testing6.csproj
Testing6/app.config
Testing6/packages.config

adding validation (middle layer and presentation layer)

---

AdminSystem/CustomerDataEntry.aspx.cs
AdminSystem/Web.config
AdminSystem/packages.config
ClassLibrary/ClassLibrary.csproj
ClassLibrary/app.config
ClassLibrary/clsCustomer.cs
ClassLibrary/packages.config
Skeleton.sln
Testing1/TestingCustomer.csproj
Testing1/app.config
Testing1/packages.config
Testing1/tstCustomer.cs
Testing2/TestingProduct.csproj
Testing2/app.config
Testing2/packages.config
Testing3/TestingStaff.csproj
Testing3/app.config
Testing3/packages.config
Testing4/TestingOrder.csproj
Testing4/app.config
Testing4/packages.config
Testing5/TestingSupply.csproj
Testing5/app.config
Testing5/packages.config
Testing6/Testing6.csproj
Testing6/app.config
Testing6/packages.config

Reverts christophersompa/phone-case#28

Revert "adding validation (middle layer and presentation layer)"

---

AdminSystem/CustomerDataEntry.aspx.cs
ClassLibrary/clsCustomer.cs
Skeleton.sln
Testing1/tstCustomer.cs

adding validation (middle layer & presentation layer)

---

AdminSystem/CustomerDataEntry.aspx
AdminSystem/CustomerViewer.aspx.cs
AdminSystem/Web.config
AdminSystem/packages.config
ClassLibrary/ClassLibrary.csproj
ClassLibrary/app.config
ClassLibrary/packages.config
Testing1/TestingCustomer.csproj
Testing1/app.config
Testing1/packages.config
Testing2/TestingProduct.csproj
Testing2/app.config
Testing2/packages.config
Testing3/TestingStaff.csproj
Testing3/app.config
Testing3/packages.config
Testing4/TestingOrder.csproj
Testing4/app.config
Testing4/packages.config
Testing5/TestingSupply.csproj
Testing5/app.config
Testing5/packages.config
Testing6/Testing6.csproj
Testing6/app.config
Testing6/packages.config

adding validation (middle and presentation) edits

---

AdminSystem/CustomerConfirmDelete.aspx
AdminSystem/CustomerConfirmDelete.aspx.cs
AdminSystem/CustomerDataEntry.aspx.cs
AdminSystem/CustomerList.aspx
AdminSystem/CustomerList.aspx.cs
AdminSystem/packages.config
ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsCustomer.cs
ClassLibrary/clsCustomerCollection.cs
ClassLibrary/packages.config
Testing1/TestingCustomer.csproj
Testing1/packages.config
Testing1/tstCustomer.cs
Testing1/tstCustomerCollection.cs
Testing2/TestingProduct.csproj
Testing2/packages.config
Testing3/TestingStaff.csproj
Testing3/packages.config
Testing4/TestingOrder.csproj
Testing4/packages.config
Testing5/TestingSupply.csproj
Testing5/packages.config
Testing6/Testing6.csproj
Testing6/packages.config

All fine and checked.
tstCustomerCollection > CountPropertyOk (test) failing apart from that all 55 tests pass!

Creating the Collection (Add/Edit/Delete/Filter)

---

AdminSystem/CustomerDataEntry.aspx
AdminSystem/CustomerDataEntry.aspx.cs
AdminSystem/CustomerList.aspx
AdminSystem/CustomerList.aspx.cs
AdminSystem/packages.config
ClassLibrary/ClassLibrary.csproj
ClassLibrary/packages.config
Testing1/TestingCustomer.csproj
Testing1/packages.config
Testing1/tstCustomerCollection.cs
Testing2/TestingProduct.csproj
Testing2/packages.config
Testing3/TestingStaff.csproj
Testing3/packages.config
Testing4/TestingOrder.csproj
Testing4/packages.config
Testing5/TestingSupply.csproj
Testing5/packages.config
Testing6/Testing6.csproj
Testing6/packages.config

Creating the Collection Methods (Delete and Filter) + Bug Fixes

---

AdminSystem/App_Code/clsSupplyCollection.cs
AdminSystem/SupplyDataEntry.aspx.cs
AdminSystem/SupplyDelete.aspx
AdminSystem/SupplyDelete.aspx.cs
AdminSystem/SupplyList.aspx
AdminSystem/SupplyList.aspx.cs
AdminSystem/packages.config
ClassLibrary/ClassLibrary.csproj
Testing1/TestingCustomer.csproj
Testing2/TestingProduct.csproj
Testing3/TestingStaff.csproj
Testing4/TestingOrder.csproj
Testing5/TestingSupply.csproj
Testing5/clsSupplyCollection.cs
Testing5/packages.config
Testing5/tstSupplyCollection.cs
Testing6/Testing6.csproj

Lab work up to date, needs corrections

Lab work up to date, needs corrections

---

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsOrderCollection.cs
Testing4/TestingOrder.csproj
Testing4/tstOrderCollection.cs

Created the Collection Class (Properties)

---

AdminSystem/OrderDataEntry.aspx.cs
AdminSystem/OrderList.aspx
AdminSystem/OrderList.aspx.cs
ClassLibrary/clsOrderCollection.cs
Testing4/tstOrderCollection.cs

Created the Methods (Add)

---

Testing1/ClassDiagram1.cd
Testing5/TestingSupply.csproj

TestingSupply.csproj fixed (failed to load)

---

AdminSystem/OrderConfirmDelete.aspx.cs
AdminSystem/OrderDataEntry.aspx.cs
AdminSystem/OrderList.aspx
AdminSystem/OrderList.aspx.cs
ClassLibrary/clsOrder.cs
ClassLibrary/clsOrderCollection.cs
Testing4/tstOrder.cs
Testing4/tstOrderCollection.cs

Tests in Collection don't pass despite being coded perfectly

Created Collection Methods Filter

---

Testing5/TestingSupply.csproj

accidentally sent the wrong one like a dick

Final final
